#The address of the agent-server
server_address = "https://0.0.0.0:8080"

#Where to store the agent-client's uuid and auth string
auth_file = "etc/auth.toml"

#How often to ping the agent-server
ping_interval = "1m"
