#Boilerplate database stuff
[database]
    address = "0.0.0.0:3306"
    name = "agent"
    user = "agent"
    pass = "agent"
    debug = true

[server]
#How many registration authorization strings to generate
    register_auth_count = 10
#How long registration authorizations are valid
    register_auth_expire = "24h"
#Enable or disable logging to systemd
    systemd_logging = true
#SSL Key path to use for https connections
    ssl_key_path = "ssl/key.pem"
#SSL Cert path to use for https connections
    ssl_cert_path = "ssl/cert.crt"
#Port for the api to listen on
    listen_port = "8080"
#Enable logging of time elapsed in API calls
    timetrack_api = true
